01_simple: src/01_simple.c
	 aarch64-linux-gnu-gcc-9 -o out/01_simple src/01_simple.c

02_mulitglitch: src/02_multiglitch.c
	aarch64-linux-gnu-gcc-9 -o out/02_multiglitch src/02_multiglitch.c

03_complex_find: src/03_complex_find.c
	aarch64-linux-gnu-gcc-9 -o out/03_complex_find src/03_complex_find.c

all: 01_simple 02_mulitglitch 03_complex_find
