name: build

on:
  push:
    # build the project on every push
    branches:
      - main
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["10.1.2"]
        include:
        - version: "10.1.2"
          DOWNLOAD_URL: "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.1.2_build/ghidra_10.1.2_PUBLIC_20220125.zip"
          PACKAGE_NAME: "ghidra_10.1.2_PUBLIC_20220125.zip"
          DIRECTORY_NAME: "ghidra_10.1.2_PUBLIC"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: setup-java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: install ghidra
      run: |
        echo "building for version ${{matrix.version}}"
        wget -q ${{matrix.DOWNLOAD_URL}}
        mkdir -p ./ghidra
        unzip -q ${{matrix.PACKAGE_NAME}} -d ghidra
    - name: build plugin
      run: |
        export CURRENT_DIR=$(pwd)
        export GHIDRA_INSTALL_DIR=${CURRENT_DIR}/ghidra/${{matrix.DIRECTORY_NAME}}
        cd ghidra_plugin && ./gradlew
    - name: Store artifcact
      uses: actions/upload-artifact@v2
      with:
        name: ${{DIRECTORY_NAME}}-ghidra-faultinjector.zip
        path: |
          ghidra_plugin/dist/*.zip
