name: build

on:
  push:
    # build the project on every push
    branches:
      - main
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["10.1.2"]
        include:
        - version: "10.1.2"
          DOWNLOAD_URL: "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.1.2_build/ghidra_10.1.2_PUBLIC_20220125.zip"
          PACKAGE_NAME: "ghidra_10.1.2_PUBLIC_20220125.zip"
          DIRECTORY_NAME: "ghidra_10.1.2_PUBLIC_20220125"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: setup-java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: install ghidra
      run: |
        echo "building for version ${{matrix.version}}"
        wget ${{matrix.DOWNLOAD_URL}}
        mkdir -p /ghidra
        unzip ${{matrix.PACKAGE_NAME}} -d /ghidra
        export GHIDRA_INSTALL_DIR=/ghidra/${{matrix.DIRECTORY_NAME}}
        cd ghidra_plugin && ./gradlew
