name: publish

on:
  release:
    types: [ created ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["10.1.2", "10.1.1"]
        include:
        - version: "10.1.2"
          DOWNLOAD_URL: "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.1.2_build/ghidra_10.1.2_PUBLIC_20220125.zip"
          PACKAGE_NAME: "ghidra_10.1.2_PUBLIC_20220125.zip"
          DIRECTORY_NAME: "ghidra_10.1.2_PUBLIC"
        - version: "10.1.1"
          DOWNLOAD_URL: "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.1.1_build/ghidra_10.1.1_PUBLIC_20211221.zip"
          PACKAGE_NAME: "ghidra_10.1.1_PUBLIC_20211221.zip"
          DIRECTORY_NAME: "ghidra_10.1.1_PUBLIC"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: setup-java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: install ghidra
      run: |
        echo "building for version ${{matrix.version}}"
        wget -q ${{matrix.DOWNLOAD_URL}}
        mkdir -p ./ghidra
        unzip -q ${{matrix.PACKAGE_NAME}} -d ghidra
    - name: build plugin
      run: |
        export CURRENT_DIR=$(pwd)
        export GHIDRA_INSTALL_DIR=${CURRENT_DIR}/ghidra/${{matrix.DIRECTORY_NAME}}
        cd ghidra_plugin && ./gradlew
    - name: Store artifcact
      uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.DIRECTORY_NAME}}-ghidra-faultinjector.zip
        path: |
          ghidra_plugin/dist/*.zip

  upload:
    name: Upload release assets
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: assets
      - name: Upload release assets
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: './assets/*'
